defaulting to mainnet for portis wallet, finding networkId from porti…
gitcoinco/web pull request #10443
Opened 2022-04-01 14:38 UTC by schultztimothy

##### Description

It looks like, when using portis wallet, there was an issue finding the networkId which is used to filter out tokens on the checkout page. 

I also was unable to switch the portis wallet to any network beside rinkeby. While looking through the docs it looks like they are expecting a network parameter https://docs.portis.io/#/quick-start. 

##### Refers/Fixes

fixes: #10429

2022-04-02 19:56 UTC, philipjonsen approved these changes

2022-04-03 06:28 UTC, thelostone-mc reviewed
lgtm. small note:  could we remove the log and commented out code

2022-04-04 15:56 UTC, schultztimothy commented
> lgtm. small note: could we remove the log and commented out code

Ahh thank you for catching that 🙌

2022-04-18 10:56 UTC, thelostone-mc approved these changes

2022-04-20 01:15 UTC, chibie requested changes

2022-04-20 01:15 UTC, chibie commented on app/assets/v2/js/cart.js
> +        console.log({ tokenDetails });
can we take out this log?

2022-04-20 14:02 UTC, thelostone-mc commented on app/assets/v2/js/cart.js
> +        console.log({ tokenDetails });
```suggestion
```

2022-04-20 20:10 UTC, chibie approved these changes

2022-04-21 12:17 UTC, merged