Implement track of grants
gitcoinco/web pull request #7245
Opened 2020-08-18 06:44 UTC by zoek1

##### Description

https://www.loom.com/share/f3e87e25d78e4628bb92623066137def

**note*
I changed start instead of following, I think this will be more meaningful
##### Refers/Fixes
https://github.com/gitcoinco/web/issues/7163
As a grrants user, I want the ability to star/unstar a grant, so that I can have a shortlist of grants to checkout later.

##### Testing

2020-08-25 12:49 UTC, danlipert requested changes
Just a few questions - also, I'm wondering if we can have the favorite count in the sidebar update as you favorite and unfavorite a grant so the count updates without having to reload or go to another page.

2020-08-25 12:49 UTC, danlipert commented on app/townsquare/models.py
> +        return Favorite.objects.filter(activity=None)
why use the `activity=None` filter to find grants instead of `Favorite.objects.filter(grant__isnull=False)`? Seems unintuitive

2020-08-25 12:49 UTC, danlipert commented on app/townsquare/models.py
> +        return Favorite.objects.filter(activity=None)
Also the related_name should probably just be `'favorites'` so you can access it like `grant.favorites`

2020-08-25 12:49 UTC, danlipert commented on app/townsquare/views.py
> +        num_favorites = request.user.favorites.filter(grant=None).all().count()
Maybe I'm misunderstanding how this works, but how does this filter give you the count of your favorite grants? Shouldn't it be `.exclude(grant=None)`?

2020-09-17 04:17 UTC, thelostone-mc commented
Closing as this got it via #7332

2020-09-17 04:17 UTC, closed without merging