updated user directory models/indexers to reflect proper production d…
gitcoinco/web pull request #7307
Opened 2020-08-31 20:03 UTC by androolloyd

…ata set types

##### Description
Correct the UserDirectory Model and Indexers are not configured with correct types/schema requirements to match what is used in production

##### Refers/Fixes
Inability to index the current userdirectory

##### Testing

2020-09-01 09:48 UTC, thelostone-mc requested changes
@androolloyd could you create a new migration instead updating the old one 
This has already been run on live

2020-09-01 13:46 UTC, androolloyd commented
Since we’re not managing the migrations with django it won’t affect anything, while the migration execution status is stored in the db as being called. 

No SQL is executed by it. 

These changes are to bring the python model in line with what’s actually being produced by prod data. 


I can create a migration that modifies the view but if we have an execution status already for this migration there isn’t a need to run anything again anyways.

2020-09-02 15:51 UTC, thelostone-mc approved these changes
Synced up with @androolloyd who's assured like the migrations files are not bring tracked and has no affect on the rest of the app.
Updating the migration file should be alright even though it's already in live

2020-09-04 14:42 UTC, merged

2020-09-06 06:12 UTC, nicc938 commented on app/dashboard/views.py
> +    remote_url = f'{settings.HAYSTACK_ELASTIC_SEARCH_URL}{path}'
nicc938