Add video demo
gitcoinco/web pull request #7309
Opened 2020-09-01 01:34 UTC by zoek1

##### Description
- Add video field to submission view
- Add field to project form
- Show video demo in the project page

https://www.loom.com/share/b6f604db4a854427a42a85cb88b71939

##### Refers/Fixes

##### Testing

2020-09-01 04:24 UTC, thelostone-mc commented
Could you list out which issue this is linked to?

2020-09-14 11:14 UTC, PixelantDesign approved these changes

2020-09-14 11:15 UTC, PixelantDesign commented
awesome!

2020-09-14 11:19 UTC, PixelantDesign commented
Looking good! @zoek1 if @jdorfman or @connoroday set up the event on  Add Event, the events will show on our events tab correct? I didn't see that in the video.

2020-09-14 21:40 UTC, frankchen07 commented
> set up the event on Add Event, the events will show on our events tab correct? I didn't see that in the video.

yes this was part of the other ticket: https://www.loom.com/share/a82ef2081ffb45e6bef233fe9214112d

it looks like as long as the calendar id is linked in the administration, using add event will show up.

===

just want to rehash adityas request above to link the issue ticket this refers to.

otherwise LGTM, looking good. Hopefully this helps sponsors review hackathon work at a greater pace, and allows folks to have a pre-recorded pitch.

2020-09-14 21:41 UTC, frankchen07 approved these changes

2020-09-15 11:06 UTC, PixelantDesign commented
yes! i dropped comment on wrong ticket  and figured out after rewatched lol

2020-09-22 23:08 UTC, octavioamu requested changes
seems some other code come in to remove the mark winner

2020-09-22 23:08 UTC, octavioamu commented on app/assets/v2/js/vue-components.js
> -    },
is this removal related?

2020-09-22 23:10 UTC, octavioamu commented on app/assets/v2/js/vue-components.js
> -    },
As I didn't saw a comment about it on the description I requested changes. Not sure if product team is aware of that changes also.

2020-09-23 11:27 UTC, PixelantDesign commented
https://github.com/gitcoinco/web/issues/7507

2020-09-23 11:31 UTC, PixelantDesign commented
>seems some other code come in to remove the mark winner
@octavioamu what do you mean here?

2020-09-30 01:06 UTC, zoek1 commented
This is included in https://github.com/gitcoinco/web/pull/7493

2020-09-30 01:06 UTC, closed without merging

2020-09-30 19:23 UTC, PixelantDesign commented
@thelostone-mc can we get this pr in first?