Feature/new look grants
gitcoinco/web pull request #7332
Opened 2020-09-04 11:30 UTC by zoek1

##### Description
- star/unstar a grant using vue
- list view of all the grants,
- Fix grant nav sort issue 

https://www.loom.com/share/8eec68f5f2d243c58968f9bd2db25a96

##### Refers/Fixes
https://github.com/gitcoinco/web/issues/7163
https://github.com/gitcoinco/web/issues/7166
https://github.com/gitcoinco/web/issues/7190

##### Testing

2020-09-04 13:21 UTC, zoek1 commented
@thelostone-mc are you have some time to check this please? 🙂

2020-09-04 13:37 UTC, octavioamu requested changes
Well done Zoek, I left just some few comments

2020-09-04 13:37 UTC, octavioamu commented on app/grants/templates/grants/shared/landing_grants.html
> +        <div class="infinite-container row" v-if="grants">
I think scroll method is not being call here so probably pagination will not work you need to use the directive `scroll.passive` (check notifications.html)

2020-09-04 13:37 UTC, octavioamu commented on app/grants/templates/grants/index.html
> +            <div id="grants-showcase">
missing v-cloak to hide the vue components until data is loaded (avoid reflow)

2020-09-04 13:37 UTC, octavioamu commented on app/grants/templates/grants/shared/landing_grants.html
> +        <!--p class="mb-0 text-center py-4" v-if="has_next">
dead code

2020-09-06 14:29 UTC, thelostone-mc commented
@zoek1 could you point this to the integration branch https://github.com/gitcoinco/web/tree/round-7-integration

2020-09-06 14:32 UTC, thelostone-mc commented
Also could you show 

- how the page looks in list view when there is no active CLR
- could you rebase with integration commits

2020-09-06 14:33 UTC, thelostone-mc commented on app/grants/templates/grants/card/front.html
> +        {% endif %}
^ indent it right
```
{% if profile.user.is_authenticated %}
    ....
{% endif %}
```

2020-09-06 14:34 UTC, thelostone-mc commented on app/grants/templates/grants/components/card.html
> +      <div class="grant-item__img col-md-1 d-md-block d-none">
^ 1 tab= 2 spaces indentation please

2020-09-06 14:36 UTC, thelostone-mc commented on app/grants/templates/grants/components/card.html
> +              </h2>
^ why is this hardcoded ?
This is something which should be available from the backend API.

2020-09-06 14:38 UTC, thelostone-mc commented on app/grants/templates/grants/components/card.html
> +            {% include 'grants/card/clr_estimate.html'  %}
shouldn't this be {% include 'grants/card/clr_estimate.html' with short=True %}

2020-09-06 14:38 UTC, thelostone-mc commented on app/grants/templates/grants/components/card.html
> +</grant-card>
^ could you redo the text and the conditions based on what's in `front.html` 
this code seems a lil outdated

2020-09-06 15:03 UTC, thelostone-mc requested changes
@zoek1 looking into this code ! A lot of things would break.
Looks like you started with an outdated branch (over a month old) and never rebased after that

I'd recommend taking the latest code and porting your css + model changes
and redoing the views + HTML changes with the latest code and ensuring you don't overwrite anything

2020-09-06 15:03 UTC, thelostone-mc commented on app/grants/templates/grants/card/front.html
> +        {% endif %}
Why are there changes in this file when this you've removed it's usage in 
https://github.com/gitcoinco/web/pull/7332/files#diff-a9ea52761a5188515132b584f9014d16L9 ?

2020-09-07 10:39 UTC, closed without merging