Feat/collections
gitcoinco/web pull request #7446
Opened 2020-09-16 20:44 UTC by zoek1

##### Description

##### Refers/Fixes

##### Testing

2020-09-17 17:04 UTC, mds1 commented
Hey @zoek1, I checked out this branch, merged the latest stable into, did a make fresh, then ran `make migrate` and got the error below:

```
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0084_grantcollections, 0084_auto_20200917_1631 in grants).
To fix them run 'python manage.py makemigrations --merge'
make: *** [migrations] Error 1
```

2020-09-18 01:31 UTC, zoek1 commented
done @mds1

2020-09-21 14:05 UTC, mds1 requested changes
Hey @zoek1, left a few comments below.

I also just did a `make fresh` but can't seem to load anything afterwards. I ran `make migrate` but it said there were no migrations to run. Let me know if this is an error on my end or if there's something we need to fix!

![image](https://user-images.githubusercontent.com/17163988/93776705-af40f900-fbd8-11ea-8f8b-4e68bfb00fed.png)

2020-09-21 19:15 UTC, owocki commented
looks relaly good!

just pulled this down to test. my feedback for v1.
1. can we move the 'save collection' button next to 'share cart' in the UI on the checkout page?
2. is it easy to add a 'featured collections' view?
3. when there are 70+ items in cart, or in a collection, the site gets very very very slow.  (a quick triage of this would be great)

v2: 
1. ability to  add/remove grants from collection after the fact
2. share collection add/remove ability with other team members (so a group of ppl can curate collections together - this can be stubbed in in the backend if it makes it easier.)

2020-09-22 07:05 UTC, zoek1 commented
@owocki i implemented the v1 and v2 requests, could you mind test it again?

2020-09-22 07:05 UTC, zoek1 commented on app/assets/v2/js/grants/index.js
> +        _alert(`Congratulations, ${getGrants.grants.length} ${getGrants.grants.length > 1 ? 'grant were' : 'grants was'} added to your cart!`, 'success');
fixed

2020-09-22 07:06 UTC, zoek1 commented on app/assets/v2/js/cart-data.js
> +  static addToCart(grantData, no_report) {
thanks, i missed this. i used the no_report on bulk operation `addAllToCart`.

2020-09-22 07:09 UTC, zoek1 commented
> Hey @zoek1, left a few comments below.
> 
> I also just did a `make fresh` but can't seem to load anything afterwards. I ran `make migrate` but it said there were no migrations to run. Let me know if this is an error on my end or if there's something we need to fix!
> 
> ![image](https://user-images.githubusercontent.com/17163988/93776705-af40f900-fbd8-11ea-8f8b-4e68bfb00fed.png)

I'm not sure what cause this error, as I remember i didn't  touch any part of such code :thinking: 

Also, i added the corresponding migrations

2020-09-22 14:54 UTC, owocki commented
my qa this am:

# showstoppers
1. i see ' cannot fund your own grant' on every grant https://bits.owocki.com/yAubpjeX
2. did something break about clr eligibility upon add to cart in this PR?  all of these grants should be eligible for CLR but it says 'not eligible for clr' in the cart https://bits.owocki.com/E0unD7wA https://bits.owocki.com/2Nuygxdp

# minor issues
1. can we add a 'no data' state for my/featured/ all collections?  right now its empty and feels broken https://bits.owocki.com/jkuZzow7
just say something like "to create a collection, add some grants to cart + click 'save to collection' at checkout"
2. when i view a collection, id like to have that collection name/desc in the unfurl info (twitter title/desc) pls  https://bits.owocki.com/6quedkOg

# enhancements
1. lets brainstorm how we can edit collections on an ongoing basis.  this will be important for ppl to be able to ongoing curate their collections.  maybe if you have a collection + you click 'save as collection' during checkout, you can be promipted to add those grants to an existing collection instead of to a new one?
2. having the ability for me to share my ability to curate a collection with someone else would be 💯 

# open questions

2020-09-22 21:38 UTC, zoek1 commented
@owocki i addressed showstoppers && minor issues

2020-09-22 21:56 UTC, owocki commented
left some comments on zoek via DMs:

- hmm i see the null state even if there are grants showing up https://bits.owocki.com/4gu9kR7P
- also the ‘add to collection’ button doesnt work, when i have no cllections.  maybe it makes more sense to have the ‘add to collection’ functionality in the “Save as Collection ” button on the cart
- so instead of having ‘save cart as collection’ it should give you the option to add them to an existing collection instead of saving them https://bits.owocki.com/yAubpnl2
- also the collections are now showing on the main grant taxonomy

2020-09-23 01:35 UTC, zoek1 commented
- [x] hmm i see the null state even if there are grants showing up https://bits.owocki.com/4gu9kR7P
- [x] also the ‘add to collection’ button doesnt work, when i have no cllections. 
- [x] instead of having ‘save cart as collection’ it should give you the option to add them to an existing collection instead of saving them https://bits.owocki.com/yAubpnl2
- [x] also the collections are now showing on the main grant taxonomy

@owocki

2020-09-23 11:47 UTC, thelostone-mc commented on app/grants/admin.py
> +    Subscription, GrantCollections,
^ GrantCollect 
Let's keep it singular

2020-09-23 11:47 UTC, thelostone-mc commented on app/grants/admin.py
> +class GrantCollectionsAdmin(admin.ModelAdmin):
^ GrantCollection

2020-09-23 11:47 UTC, thelostone-mc commented on app/grants/admin.py
> +admin.site.register(GrantCollections, GrantCollectionsAdmin)
GrantCollection

2020-09-23 11:48 UTC, thelostone-mc commented on app/grants/models.py
> +class GrantCollections(SuperModel):
GrantCollection

2020-09-23 14:59 UTC, thelostone-mc approved these changes

2020-09-23 15:20 UTC, merged