Changes to the Landing page
gitcoinco/web pull request #8176
Opened 2020-12-23 14:34 UTC by nglglhtr

* remove "Developers" &  "Network"
  * add 2 new descriptions with buttons to "What is Gitcoin" sec.
  * move newsletter section to 3rd screen

##### Description

##### Refers/Fixes

##### Testing

2020-12-29 10:26 UTC, aamustapha approved these changes
Good work

2021-01-04 05:47 UTC, thelostone-mc requested changes
Left a few comments!
Could you also add a screenshot and ensure it also works for mobile display

2021-01-04 05:47 UTC, thelostone-mc commented on app/assets/landingpage/app.css
> +  padding: 3em 0em; }
^ could you undo all these indent changes

2021-01-04 05:47 UTC, thelostone-mc commented on app/assets/landingpage/section_whatisgitcoin.scss
>  }
could you reindent this file with 1 tab = 2 spaces (just like the other files)

2021-01-04 05:47 UTC, thelostone-mc commented on app/retail/templates/home/index2020.html
> -      <img src="/static/v2/images/helmet-white.svg">
If this is not used anywhere -> can we remove the image as well ?

2021-01-04 05:47 UTC, thelostone-mc commented on app/retail/templates/home/index2020.html
> +</section>
^ indent fix needed

2021-01-05 13:51 UTC, PixelantDesign commented
@nglglhtr could you post a video?

2021-01-06 15:03 UTC, nglglhtr commented
adding the copy to be added here: https://docs.google.com/document/d/1cDmUr80AbL1HfYLLou8lvIehVjGt-hw9ddXK9uueAkU/edit#

2021-01-08 13:32 UTC, nglglhtr commented
> @nglglhtr could you post a video?

here's the link to a desktop scroll video: https://www.icloud.com/iclouddrive/04Y5aseNyERZFCk0yJ7XuY1IQ#Screen_Recording_2021-01-08_at_6.59.52_PM

2021-01-08 21:44 UTC, frankchen07 commented
Minor changes:

"Get grant funding" -> can we keep the capitalization consistent? -> "Get Grant Funding" 

Does "Enter Gitcoin" just put them back on Townsquare? I would recommend removing the ability to just "enter" and end up on Townsquare because we've received plenty of feedback on how folks are confused when they get there. The onboarding idea for the landing page was to direct them down one specific path to reduce the problem of confusion.

<img width="261" alt="Screen Shot 2021-01-08 at 13 39 05" src="https://user-images.githubusercontent.com/7516920/104066825-e8689d80-51b6-11eb-92e8-34abe078f9b8.png">

Is there any way to help this text stand out, or feel more like "points" rather than just text thrown on there? It's a bit hard to read:

<img width="527" alt="Screen Shot 2021-01-08 at 13 38 22" src="https://user-images.githubusercontent.com/7516920/104066794-db4bae80-51b6-11eb-9c5c-6a9038351fee.png">

> up skill

I think it's supposed to be one word "upskill".

> ...the ecosystem, Get involved...

Should be a period. "...the ecosystem. Get involved..."

The rest looks pretty good. Just from watching the video though, I still feel like the zoom is pretty strong. I would want to see more with less scrolling, but pp to design though cc @PixelantDesign

2021-01-12 11:58 UTC, chibie approved these changes

2021-01-12 16:07 UTC, nglglhtr commented
can we merge this?

2021-01-12 17:05 UTC, frankchen07 commented
I had a comment with a bunch of changes @nglglhtr, did they make it in?

2021-01-13 09:54 UTC, nglglhtr commented
> Does "Enter Gitcoin" just put them back on Townsquare? I would recommend removing the ability to just "enter" and end up on Townsquare because we've received plenty of feedback on how folks are confused when they get there. The onboarding idea for the landing page was to direct them down one specific path to reduce the problem of confusion.

Yes it does - can remove the button altogether for now

2021-01-13 11:00 UTC, nglglhtr commented
Fixed the heights of the buildings in the background to create more space for the text, here's an 8x video: 

https://user-images.githubusercontent.com/10832414/104443599-a6779700-55bc-11eb-91c0-7fed804b599f.mp4

2021-01-13 21:27 UTC, frankchen07 commented
@nglglhtr, the all caps for the actions look a little funny to me, and I feel like it crowds the space a little bit. 

Can we just simplify and remove all of the sub-text (START an open source project. LEARN ...etc.), and leave the larger title text there?

So just keep:

<img width="257" alt="Screen Shot 2021-01-13 at 13 26 38" src="https://user-images.githubusercontent.com/7516920/104512414-05c8ad80-55a3-11eb-96b4-16df32f18c90.png">

Everything else looks good to go! Thanks for helping out with these changes! :)

2021-01-14 07:49 UTC, thelostone-mc commented
@PixelantDesign  + @frankchen07 ddo hit approve once the PR Is good from your side and I can get it in after that

2021-01-14 08:13 UTC, nglglhtr commented
> @nglglhtr, the all caps for the actions look a little funny to me, and I feel like it crowds the space a little bit.
> 
> Can we just simplify and remove all of the sub-text (START an open source project. LEARN ...etc.), and leave the larger title text there?

Yes, for sure, not a problem; I do not really have a strong opinion for or against a design change - my UI skillz are pretty much nonexistent lol; relying on yours & @PixelantDesign's judgement here :)

2021-01-14 09:57 UTC, nglglhtr commented
Updated screenshot:
<img width="1904" alt="image" src="https://user-images.githubusercontent.com/10832414/104575338-059ce080-567d-11eb-8aed-f56bab01b808.png">

2021-01-14 18:09 UTC, frankchen07 commented
I read the copy a few times to make sure that even though we remove the sub-text we're still conveying 90+% using the title, larger text. No worries, text is easy to change if we decide to do so with any new rebranding copy work.

2021-01-14 18:09 UTC, frankchen07 approved these changes
LGTM!

2021-01-15 05:14 UTC, thelostone-mc approved these changes

2021-01-15 05:14 UTC, merged