feat(binance): integrate BUSD for bounties and hackathons 2
gitcoinco/web pull request #8213
Opened 2021-01-07 15:53 UTC by chibie

##### Description

sequel to #8121

2021-01-07 16:01 UTC, aamustapha requested changes

2021-01-08 09:47 UTC, chibie commented on app/dashboard/templates/dashboard/hackathon/new_bounty.html
> +    <script src="https://cdn.jsdelivr.net/npm/@binance-chain/javascript-sdk@4.1.1/lib/index.min.js"></script>
should i take it out?

2021-01-08 09:48 UTC, chibie commented on app/dashboard/templates/dashboard/hackathon/new_bounty.html
> +    <script src="https://cdn.jsdelivr.net/npm/@binance-chain/javascript-sdk@4.1.1/lib/index.min.js"></script>
done!

2021-01-08 15:25 UTC, aamustapha approved these changes

2021-01-08 15:48 UTC, thelostone-mc approved these changes

2021-01-11 13:02 UTC, merged