WIP grants/rsk
gitcoinco/web pull request #8402
Opened 2021-02-17 13:22 UTC by thelostone-mc

##### Description

- [ ] Grant Creation
- [ ] Update Grant Details
- [ ] Contribute Grant
- [ ] Backend logic sync

2021-02-25 16:09 UTC, chibie requested changes

2021-02-25 16:09 UTC, chibie commented on app/assets/v2/js/grants/cart/rsk_extension.js
> +        console.log(response);
you can remove the logs here

2021-02-25 16:09 UTC, chibie commented on app/assets/v2/js/grants/funding.js
> +    tokenDefault = 'RSK';
tokenDefault should be R-BTC

2021-02-26 11:59 UTC, thelostone-mc commented on app/assets/v2/js/grants/funding.js
> +    tokenDefault = 'RSK';
Oh fuck ! nice catch man

2021-02-26 12:03 UTC, thelostone-mc commented on app/assets/v2/js/grants/cart/rsk_extension.js
> +        console.log(response);
done

2021-03-01 14:05 UTC, chibie approved these changes

2021-03-01 14:24 UTC, merged