alert -> error to danger
gitcoinco/web pull request #8725
Opened 2021-03-29 15:37 UTC by thelostone-mc

##### Description

https://gitcoincore.slack.com/archives/G01LRE6F39A/p1617025362000900

2021-03-29 15:59 UTC, gdixon requested changes
A couple of `.on('error')` events got caught up in the replacement

2021-03-29 15:59 UTC, gdixon commented on app/assets/v2/js/board.js
> +            .on('danger', function(err) {
These need changing back to `.on('error')`

2021-03-29 15:59 UTC, gdixon commented on app/assets/v2/js/board.js
> +              }).on('danger', function(err) {
`.on('error')`

2021-03-29 15:59 UTC, gdixon commented on app/assets/v2/js/board.js
> +              }).on('danger', function(err) {
`.on('error')`

2021-03-29 15:59 UTC, gdixon commented on app/assets/v2/js/board.js
> +      }).on('danger', function(err) {
`.on('error')`

2021-03-29 15:59 UTC, gdixon commented on app/assets/v2/js/board.js
> +          }).on('danger', async(error, receipt) => {
`.on('error')`

2021-03-30 09:50 UTC, thelostone-mc commented
@gdixon updated 🙌

2021-03-30 10:57 UTC, gdixon approved these changes

2021-03-30 11:00 UTC, merged