add survey section to grants emails
gitcoinco/web pull request #9490
Opened 2021-09-16 22:18 UTC by octavioamu

##### Description
Add survey section to new_grant creation and thank_you_for_supporting emails with links 

##### Refers/Fixes

Ref https://gitcoin.atlassian.net/browse/GITC-421
##### Testing

![image](https://user-images.githubusercontent.com/1358093/133692908-87a2edd7-33f8-4991-8bd5-8af8e8d6bf9a.png)
![image](https://user-images.githubusercontent.com/1358093/133692919-c7e988d1-f5ec-4f8f-8807-92923e18147c.png)

2021-09-17 01:39 UTC, chibie requested changes

2021-09-17 01:39 UTC, chibie commented on app/retail/templates/emails/grants/new_grant.html
> +  <div class="">
take out empty attribute?

2021-09-17 01:39 UTC, chibie commented on app/retail/templates/emails/grants/thank_you_for_supporting.html
> +  <div class="">
same here

2021-09-20 13:13 UTC, thelostone-mc approved these changes

2021-09-20 13:43 UTC, zacheryschiller approved these changes

2021-09-20 13:46 UTC, merged