Claim date
gitcoinco/web pull request #9544
Opened 2021-10-01 09:37 UTC by thelostone-mc

##### Description

- add claim start and end data to Grant CLR
- uses that info to show info on if round is 
 - upcoming
 - active
 - ended
 - in claim phase
 
 This does not make any changes to the landing page on explorer as discussed with @frankchen07 as having a generic claim with diff periods does not scale
 
 

##### Refers/Fixes

https://gitcoin.atlassian.net/browse/GITC-466

##### Testing

2021-10-01 18:39 UTC, ksolo requested changes
Can you update the model tests to reflect the new properties?
https://github.com/gitcoinco/web/blob/master/app/grants/tests/models/test_grant_clr.py

2021-10-01 19:28 UTC, frankchen07 commented
@thelostone-mc this looks awesome!

1. Is there a way to change "Claim - Active ends {countdown}" when it's the claiming period? The statement doesn't really make sense. "Round - Ended" and "Round - Proposed" look good though.

2. How are you toggling which status appears? I'm a little confused on that. It looks like there's proposed, active, ended, claim active

cc @PixelantDesign this PR can handle the claim period for GR11 (since there's only one banner on the homepage for GR11), but for future CLR (side) rounds, we can choose to surface these claim dates either on the homepage or elsewhere in grant management. We can chat more about what a good solution here would look like.

2021-10-01 19:29 UTC, frankchen07 commented
reviewed the video on https://github.com/gitcoinco/web/pull/9549, left a couple of comments

2021-10-04 11:45 UTC, chibie requested changes

2021-10-04 11:45 UTC, chibie commented on app/assets/v2/js/grants/index.js
> +          console.log(claim_end_date);
and some merge conflicts

2021-10-04 13:43 UTC, ksolo approved these changes

2021-10-04 13:45 UTC, chibie approved these changes

2021-10-04 13:46 UTC, Jer-Sch approved these changes

2021-10-04 13:51 UTC, merged